class AcceptableTaskError(Exception):
    pass


class BadHash(Exception):
    pass
